INSERT INTO APP_USER VALUES(999,'Jatin','Sahu','j@j.com','1234');
INSERT INTO SUBJECT_STREAMS VALUES(999,'C');
INSERT INTO SUBJECT_STREAMS VALUES(998,'C++');
INSERT INTO SUBJECT_STREAMS VALUES(997,'Python');
INSERT INTO SUBJECT_STREAMS VALUES(996,'Java');
INSERT INTO SUBJECT_STREAMS VALUES(995,'SQL');